// Code generated by ent, DO NOT EDIT.

package cep_ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/stark-sim/cephalon-ent/pkg/cep_ent/model"
	"github.com/stark-sim/cephalon-ent/pkg/cep_ent/predicate"
	"github.com/stark-sim/cephalon-ent/pkg/cep_ent/user"
	"github.com/stark-sim/cephalon-ent/pkg/cep_ent/usermodel"
)

// UserModelQuery is the builder for querying UserModel entities.
type UserModelQuery struct {
	config
	ctx        *QueryContext
	order      []usermodel.OrderOption
	inters     []Interceptor
	predicates []predicate.UserModel
	withUser   *UserQuery
	withModel  *ModelQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserModelQuery builder.
func (umq *UserModelQuery) Where(ps ...predicate.UserModel) *UserModelQuery {
	umq.predicates = append(umq.predicates, ps...)
	return umq
}

// Limit the number of records to be returned by this query.
func (umq *UserModelQuery) Limit(limit int) *UserModelQuery {
	umq.ctx.Limit = &limit
	return umq
}

// Offset to start from.
func (umq *UserModelQuery) Offset(offset int) *UserModelQuery {
	umq.ctx.Offset = &offset
	return umq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (umq *UserModelQuery) Unique(unique bool) *UserModelQuery {
	umq.ctx.Unique = &unique
	return umq
}

// Order specifies how the records should be ordered.
func (umq *UserModelQuery) Order(o ...usermodel.OrderOption) *UserModelQuery {
	umq.order = append(umq.order, o...)
	return umq
}

// QueryUser chains the current query on the "user" edge.
func (umq *UserModelQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: umq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := umq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := umq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usermodel.Table, usermodel.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usermodel.UserTable, usermodel.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(umq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryModel chains the current query on the "model" edge.
func (umq *UserModelQuery) QueryModel() *ModelQuery {
	query := (&ModelClient{config: umq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := umq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := umq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usermodel.Table, usermodel.FieldID, selector),
			sqlgraph.To(model.Table, model.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usermodel.ModelTable, usermodel.ModelColumn),
		)
		fromU = sqlgraph.SetNeighbors(umq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UserModel entity from the query.
// Returns a *NotFoundError when no UserModel was found.
func (umq *UserModelQuery) First(ctx context.Context) (*UserModel, error) {
	nodes, err := umq.Limit(1).All(setContextOp(ctx, umq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usermodel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (umq *UserModelQuery) FirstX(ctx context.Context) *UserModel {
	node, err := umq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserModel ID from the query.
// Returns a *NotFoundError when no UserModel ID was found.
func (umq *UserModelQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = umq.Limit(1).IDs(setContextOp(ctx, umq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usermodel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (umq *UserModelQuery) FirstIDX(ctx context.Context) int64 {
	id, err := umq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserModel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserModel entity is found.
// Returns a *NotFoundError when no UserModel entities are found.
func (umq *UserModelQuery) Only(ctx context.Context) (*UserModel, error) {
	nodes, err := umq.Limit(2).All(setContextOp(ctx, umq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usermodel.Label}
	default:
		return nil, &NotSingularError{usermodel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (umq *UserModelQuery) OnlyX(ctx context.Context) *UserModel {
	node, err := umq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserModel ID in the query.
// Returns a *NotSingularError when more than one UserModel ID is found.
// Returns a *NotFoundError when no entities are found.
func (umq *UserModelQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = umq.Limit(2).IDs(setContextOp(ctx, umq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usermodel.Label}
	default:
		err = &NotSingularError{usermodel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (umq *UserModelQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := umq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserModels.
func (umq *UserModelQuery) All(ctx context.Context) ([]*UserModel, error) {
	ctx = setContextOp(ctx, umq.ctx, "All")
	if err := umq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UserModel, *UserModelQuery]()
	return withInterceptors[[]*UserModel](ctx, umq, qr, umq.inters)
}

// AllX is like All, but panics if an error occurs.
func (umq *UserModelQuery) AllX(ctx context.Context) []*UserModel {
	nodes, err := umq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserModel IDs.
func (umq *UserModelQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if umq.ctx.Unique == nil && umq.path != nil {
		umq.Unique(true)
	}
	ctx = setContextOp(ctx, umq.ctx, "IDs")
	if err = umq.Select(usermodel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (umq *UserModelQuery) IDsX(ctx context.Context) []int64 {
	ids, err := umq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (umq *UserModelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, umq.ctx, "Count")
	if err := umq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, umq, querierCount[*UserModelQuery](), umq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (umq *UserModelQuery) CountX(ctx context.Context) int {
	count, err := umq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (umq *UserModelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, umq.ctx, "Exist")
	switch _, err := umq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("cep_ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (umq *UserModelQuery) ExistX(ctx context.Context) bool {
	exist, err := umq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserModelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (umq *UserModelQuery) Clone() *UserModelQuery {
	if umq == nil {
		return nil
	}
	return &UserModelQuery{
		config:     umq.config,
		ctx:        umq.ctx.Clone(),
		order:      append([]usermodel.OrderOption{}, umq.order...),
		inters:     append([]Interceptor{}, umq.inters...),
		predicates: append([]predicate.UserModel{}, umq.predicates...),
		withUser:   umq.withUser.Clone(),
		withModel:  umq.withModel.Clone(),
		// clone intermediate query.
		sql:  umq.sql.Clone(),
		path: umq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (umq *UserModelQuery) WithUser(opts ...func(*UserQuery)) *UserModelQuery {
	query := (&UserClient{config: umq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	umq.withUser = query
	return umq
}

// WithModel tells the query-builder to eager-load the nodes that are connected to
// the "model" edge. The optional arguments are used to configure the query builder of the edge.
func (umq *UserModelQuery) WithModel(opts ...func(*ModelQuery)) *UserModelQuery {
	query := (&ModelClient{config: umq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	umq.withModel = query
	return umq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,string"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UserModel.Query().
//		GroupBy(usermodel.FieldCreatedBy).
//		Aggregate(cep_ent.Count()).
//		Scan(ctx, &v)
func (umq *UserModelQuery) GroupBy(field string, fields ...string) *UserModelGroupBy {
	umq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UserModelGroupBy{build: umq}
	grbuild.flds = &umq.ctx.Fields
	grbuild.label = usermodel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedBy int64 `json:"created_by,string"`
//	}
//
//	client.UserModel.Query().
//		Select(usermodel.FieldCreatedBy).
//		Scan(ctx, &v)
func (umq *UserModelQuery) Select(fields ...string) *UserModelSelect {
	umq.ctx.Fields = append(umq.ctx.Fields, fields...)
	sbuild := &UserModelSelect{UserModelQuery: umq}
	sbuild.label = usermodel.Label
	sbuild.flds, sbuild.scan = &umq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UserModelSelect configured with the given aggregations.
func (umq *UserModelQuery) Aggregate(fns ...AggregateFunc) *UserModelSelect {
	return umq.Select().Aggregate(fns...)
}

func (umq *UserModelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range umq.inters {
		if inter == nil {
			return fmt.Errorf("cep_ent: uninitialized interceptor (forgotten import cep_ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, umq); err != nil {
				return err
			}
		}
	}
	for _, f := range umq.ctx.Fields {
		if !usermodel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("cep_ent: invalid field %q for query", f)}
		}
	}
	if umq.path != nil {
		prev, err := umq.path(ctx)
		if err != nil {
			return err
		}
		umq.sql = prev
	}
	return nil
}

func (umq *UserModelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserModel, error) {
	var (
		nodes       = []*UserModel{}
		_spec       = umq.querySpec()
		loadedTypes = [2]bool{
			umq.withUser != nil,
			umq.withModel != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UserModel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UserModel{config: umq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(umq.modifiers) > 0 {
		_spec.Modifiers = umq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, umq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := umq.withUser; query != nil {
		if err := umq.loadUser(ctx, query, nodes, nil,
			func(n *UserModel, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := umq.withModel; query != nil {
		if err := umq.loadModel(ctx, query, nodes, nil,
			func(n *UserModel, e *Model) { n.Edges.Model = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (umq *UserModelQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UserModel, init func(*UserModel), assign func(*UserModel, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserModel)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (umq *UserModelQuery) loadModel(ctx context.Context, query *ModelQuery, nodes []*UserModel, init func(*UserModel), assign func(*UserModel, *Model)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*UserModel)
	for i := range nodes {
		fk := nodes[i].ModelID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(model.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "model_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (umq *UserModelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := umq.querySpec()
	if len(umq.modifiers) > 0 {
		_spec.Modifiers = umq.modifiers
	}
	_spec.Node.Columns = umq.ctx.Fields
	if len(umq.ctx.Fields) > 0 {
		_spec.Unique = umq.ctx.Unique != nil && *umq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, umq.driver, _spec)
}

func (umq *UserModelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usermodel.Table, usermodel.Columns, sqlgraph.NewFieldSpec(usermodel.FieldID, field.TypeInt64))
	_spec.From = umq.sql
	if unique := umq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if umq.path != nil {
		_spec.Unique = true
	}
	if fields := umq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usermodel.FieldID)
		for i := range fields {
			if fields[i] != usermodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if umq.withUser != nil {
			_spec.Node.AddColumnOnce(usermodel.FieldUserID)
		}
		if umq.withModel != nil {
			_spec.Node.AddColumnOnce(usermodel.FieldModelID)
		}
	}
	if ps := umq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := umq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := umq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := umq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (umq *UserModelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(umq.driver.Dialect())
	t1 := builder.Table(usermodel.Table)
	columns := umq.ctx.Fields
	if len(columns) == 0 {
		columns = usermodel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if umq.sql != nil {
		selector = umq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if umq.ctx.Unique != nil && *umq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range umq.modifiers {
		m(selector)
	}
	for _, p := range umq.predicates {
		p(selector)
	}
	for _, p := range umq.order {
		p(selector)
	}
	if offset := umq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := umq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (umq *UserModelQuery) Modify(modifiers ...func(s *sql.Selector)) *UserModelSelect {
	umq.modifiers = append(umq.modifiers, modifiers...)
	return umq.Select()
}

// UserModelGroupBy is the group-by builder for UserModel entities.
type UserModelGroupBy struct {
	selector
	build *UserModelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (umgb *UserModelGroupBy) Aggregate(fns ...AggregateFunc) *UserModelGroupBy {
	umgb.fns = append(umgb.fns, fns...)
	return umgb
}

// Scan applies the selector query and scans the result into the given value.
func (umgb *UserModelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, umgb.build.ctx, "GroupBy")
	if err := umgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserModelQuery, *UserModelGroupBy](ctx, umgb.build, umgb, umgb.build.inters, v)
}

func (umgb *UserModelGroupBy) sqlScan(ctx context.Context, root *UserModelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(umgb.fns))
	for _, fn := range umgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*umgb.flds)+len(umgb.fns))
		for _, f := range *umgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*umgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := umgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UserModelSelect is the builder for selecting fields of UserModel entities.
type UserModelSelect struct {
	*UserModelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ums *UserModelSelect) Aggregate(fns ...AggregateFunc) *UserModelSelect {
	ums.fns = append(ums.fns, fns...)
	return ums
}

// Scan applies the selector query and scans the result into the given value.
func (ums *UserModelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ums.ctx, "Select")
	if err := ums.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UserModelQuery, *UserModelSelect](ctx, ums.UserModelQuery, ums, ums.inters, v)
}

func (ums *UserModelSelect) sqlScan(ctx context.Context, root *UserModelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ums.fns))
	for _, fn := range ums.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ums.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ums.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ums *UserModelSelect) Modify(modifiers ...func(s *sql.Selector)) *UserModelSelect {
	ums.modifiers = append(ums.modifiers, modifiers...)
	return ums
}
