// Code generated by ent, DO NOT EDIT.

package bill

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the bill type in the database.
	Label = "bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldIsAdd holds the string denoting the is_add field in the database.
	FieldIsAdd = "is_add"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldSerialNumber holds the string denoting the serial_number field in the database.
	FieldSerialNumber = "serial_number"
	// FieldWalletID holds the string denoting the wallet_id field in the database.
	FieldWalletID = "wallet_id"
	// FieldCep holds the string denoting the cep field in the database.
	FieldCep = "cep"
	// FieldReasonID holds the string denoting the reason_id field in the database.
	FieldReasonID = "reason_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMarketBillID holds the string denoting the market_bill_id field in the database.
	FieldMarketBillID = "market_bill_id"
	// FieldPlatformWalletID holds the string denoting the platform_wallet_id field in the database.
	FieldPlatformWalletID = "platform_wallet_id"
	// FieldPlatformCep holds the string denoting the platform_cep field in the database.
	FieldPlatformCep = "platform_cep"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeWallet holds the string denoting the wallet edge name in mutations.
	EdgeWallet = "wallet"
	// EdgePlatformWallet holds the string denoting the platform_wallet edge name in mutations.
	EdgePlatformWallet = "platform_wallet"
	// EdgeRechargeOrder holds the string denoting the recharge_order edge name in mutations.
	EdgeRechargeOrder = "recharge_order"
	// EdgeMissionConsumeOrder holds the string denoting the mission_consume_order edge name in mutations.
	EdgeMissionConsumeOrder = "mission_consume_order"
	// EdgeMissionProduceOrder holds the string denoting the mission_produce_order edge name in mutations.
	EdgeMissionProduceOrder = "mission_produce_order"
	// Table holds the table name of the bill in the database.
	Table = "bills"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "bills"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// WalletTable is the table that holds the wallet relation/edge.
	WalletTable = "bills"
	// WalletInverseTable is the table name for the Wallet entity.
	// It exists in this package in order to avoid circular dependency with the "wallet" package.
	WalletInverseTable = "wallets"
	// WalletColumn is the table column denoting the wallet relation/edge.
	WalletColumn = "wallet_id"
	// PlatformWalletTable is the table that holds the platform_wallet relation/edge.
	PlatformWalletTable = "bills"
	// PlatformWalletInverseTable is the table name for the PlatformWallet entity.
	// It exists in this package in order to avoid circular dependency with the "platformwallet" package.
	PlatformWalletInverseTable = "platform_wallets"
	// PlatformWalletColumn is the table column denoting the platform_wallet relation/edge.
	PlatformWalletColumn = "platform_wallet_id"
	// RechargeOrderTable is the table that holds the recharge_order relation/edge.
	RechargeOrderTable = "bills"
	// RechargeOrderInverseTable is the table name for the RechargeOrder entity.
	// It exists in this package in order to avoid circular dependency with the "rechargeorder" package.
	RechargeOrderInverseTable = "recharge_orders"
	// RechargeOrderColumn is the table column denoting the recharge_order relation/edge.
	RechargeOrderColumn = "reason_id"
	// MissionConsumeOrderTable is the table that holds the mission_consume_order relation/edge.
	MissionConsumeOrderTable = "bills"
	// MissionConsumeOrderInverseTable is the table name for the MissionConsumeOrder entity.
	// It exists in this package in order to avoid circular dependency with the "missionconsumeorder" package.
	MissionConsumeOrderInverseTable = "mission_consume_orders"
	// MissionConsumeOrderColumn is the table column denoting the mission_consume_order relation/edge.
	MissionConsumeOrderColumn = "reason_id"
	// MissionProduceOrderTable is the table that holds the mission_produce_order relation/edge.
	MissionProduceOrderTable = "bills"
	// MissionProduceOrderInverseTable is the table name for the MissionProduceOrder entity.
	// It exists in this package in order to avoid circular dependency with the "missionproduceorder" package.
	MissionProduceOrderInverseTable = "mission_produce_orders"
	// MissionProduceOrderColumn is the table column denoting the mission_produce_order relation/edge.
	MissionProduceOrderColumn = "reason_id"
)

// Columns holds all SQL columns for bill fields.
var Columns = []string{
	FieldID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldType,
	FieldIsAdd,
	FieldUserID,
	FieldSerialNumber,
	FieldWalletID,
	FieldCep,
	FieldReasonID,
	FieldStatus,
	FieldMarketBillID,
	FieldPlatformWalletID,
	FieldPlatformCep,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy int64
	// DefaultUpdatedBy holds the default value on creation for the "updated_by" field.
	DefaultUpdatedBy int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt time.Time
	// DefaultIsAdd holds the default value on creation for the "is_add" field.
	DefaultIsAdd bool
	// DefaultUserID holds the default value on creation for the "user_id" field.
	DefaultUserID int64
	// DefaultSerialNumber holds the default value on creation for the "serial_number" field.
	DefaultSerialNumber string
	// DefaultWalletID holds the default value on creation for the "wallet_id" field.
	DefaultWalletID int64
	// DefaultCep holds the default value on creation for the "cep" field.
	DefaultCep int64
	// DefaultReasonID holds the default value on creation for the "reason_id" field.
	DefaultReasonID int64
	// DefaultMarketBillID holds the default value on creation for the "market_bill_id" field.
	DefaultMarketBillID int64
	// DefaultPlatformWalletID holds the default value on creation for the "platform_wallet_id" field.
	DefaultPlatformWalletID int64
	// DefaultPlatformCep holds the default value on creation for the "platform_cep" field.
	DefaultPlatformCep int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() int64
)

// Type defines the type for the "type" enum field.
type Type string

// TypeMissionConsume is the default value of the Type enum.
const DefaultType = TypeMissionConsume

// Type values.
const (
	TypeMissionConsume Type = "mission_consume"
	TypeMissionProduce Type = "mission_produce"
	TypeRecharge       Type = "recharge"
)

func (_type Type) String() string {
	return string(_type)
}

// TypeValidator is a validator for the "type" field enum values. It is called by the builders before save.
func TypeValidator(_type Type) error {
	switch _type {
	case TypeMissionConsume, TypeMissionProduce, TypeRecharge:
		return nil
	default:
		return fmt.Errorf("bill: invalid enum value for type field: %q", _type)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusCanceled Status = "canceled"
	StatusDone     Status = "done"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusCanceled, StatusDone:
		return nil
	default:
		return fmt.Errorf("bill: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Bill queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByIsAdd orders the results by the is_add field.
func ByIsAdd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsAdd, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// BySerialNumber orders the results by the serial_number field.
func BySerialNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSerialNumber, opts...).ToFunc()
}

// ByWalletID orders the results by the wallet_id field.
func ByWalletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWalletID, opts...).ToFunc()
}

// ByCep orders the results by the cep field.
func ByCep(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCep, opts...).ToFunc()
}

// ByReasonID orders the results by the reason_id field.
func ByReasonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReasonID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByMarketBillID orders the results by the market_bill_id field.
func ByMarketBillID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMarketBillID, opts...).ToFunc()
}

// ByPlatformWalletID orders the results by the platform_wallet_id field.
func ByPlatformWalletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformWalletID, opts...).ToFunc()
}

// ByPlatformCep orders the results by the platform_cep field.
func ByPlatformCep(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformCep, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByWalletField orders the results by wallet field.
func ByWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByPlatformWalletField orders the results by platform_wallet field.
func ByPlatformWalletField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlatformWalletStep(), sql.OrderByField(field, opts...))
	}
}

// ByRechargeOrderField orders the results by recharge_order field.
func ByRechargeOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRechargeOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByMissionConsumeOrderField orders the results by mission_consume_order field.
func ByMissionConsumeOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMissionConsumeOrderStep(), sql.OrderByField(field, opts...))
	}
}

// ByMissionProduceOrderField orders the results by mission_produce_order field.
func ByMissionProduceOrderField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMissionProduceOrderStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, WalletTable, WalletColumn),
	)
}
func newPlatformWalletStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlatformWalletInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlatformWalletTable, PlatformWalletColumn),
	)
}
func newRechargeOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RechargeOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RechargeOrderTable, RechargeOrderColumn),
	)
}
func newMissionConsumeOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MissionConsumeOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MissionConsumeOrderTable, MissionConsumeOrderColumn),
	)
}
func newMissionProduceOrderStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MissionProduceOrderInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MissionProduceOrderTable, MissionProduceOrderColumn),
	)
}
