// Code generated by ent, DO NOT EDIT.

package lottochancerule

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/stark-sim/cephalon-ent/pkg/enums"
)

const (
	// Label holds the string label denoting the lottochancerule type in the database.
	Label = "lotto_chance_rule"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldLottoID holds the string denoting the lotto_id field in the database.
	FieldLottoID = "lotto_id"
	// FieldCondition holds the string denoting the condition field in the database.
	FieldCondition = "condition"
	// FieldAwardCount holds the string denoting the award_count field in the database.
	FieldAwardCount = "award_count"
	// FieldRechargeAmount holds the string denoting the recharge_amount field in the database.
	FieldRechargeAmount = "recharge_amount"
	// EdgeLotto holds the string denoting the lotto edge name in mutations.
	EdgeLotto = "lotto"
	// Table holds the table name of the lottochancerule in the database.
	Table = "lotto_chance_rules"
	// LottoTable is the table that holds the lotto relation/edge.
	LottoTable = "lotto_chance_rules"
	// LottoInverseTable is the table name for the Lotto entity.
	// It exists in this package in order to avoid circular dependency with the "lotto" package.
	LottoInverseTable = "lottos"
	// LottoColumn is the table column denoting the lotto relation/edge.
	LottoColumn = "lotto_id"
)

// Columns holds all SQL columns for lottochancerule fields.
var Columns = []string{
	FieldID,
	FieldCreatedBy,
	FieldUpdatedBy,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldLottoID,
	FieldCondition,
	FieldAwardCount,
	FieldRechargeAmount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedBy holds the default value on creation for the "created_by" field.
	DefaultCreatedBy int64
	// DefaultUpdatedBy holds the default value on creation for the "updated_by" field.
	DefaultUpdatedBy int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt time.Time
	// DefaultLottoID holds the default value on creation for the "lotto_id" field.
	DefaultLottoID int64
	// DefaultAwardCount holds the default value on creation for the "award_count" field.
	DefaultAwardCount int64
	// DefaultRechargeAmount holds the default value on creation for the "recharge_amount" field.
	DefaultRechargeAmount int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() int64
)

const DefaultCondition enums.LottoCondition = "unknown"

// ConditionValidator is a validator for the "condition" field enum values. It is called by the builders before save.
func ConditionValidator(c enums.LottoCondition) error {
	switch c {
	case "unknown", "register", "invite_register", "recharge":
		return nil
	default:
		return fmt.Errorf("lottochancerule: invalid enum value for condition field: %q", c)
	}
}

// OrderOption defines the ordering options for the LottoChanceRule queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByLottoID orders the results by the lotto_id field.
func ByLottoID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLottoID, opts...).ToFunc()
}

// ByCondition orders the results by the condition field.
func ByCondition(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCondition, opts...).ToFunc()
}

// ByAwardCount orders the results by the award_count field.
func ByAwardCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAwardCount, opts...).ToFunc()
}

// ByRechargeAmount orders the results by the recharge_amount field.
func ByRechargeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRechargeAmount, opts...).ToFunc()
}

// ByLottoField orders the results by lotto field.
func ByLottoField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLottoStep(), sql.OrderByField(field, opts...))
	}
}
func newLottoStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LottoInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LottoTable, LottoColumn),
	)
}
